name: Deploy Frontend to S3 + CloudFront

on:
  push:
    branches: [ main ]  # deploy on pushes to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write       # required for OIDC authentication
      contents: read        # needed to checkout repository

    steps:
      # Checkout the repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # Configure AWS credentials via OIDC
      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::905418230693:role/GitHub-S3-Deployer-Role
          aws-region: us-east-2

      # Replace placeholder with actual API URL
      - name: Inject API URL
        run: |
          sed -i "s|REPLACE_WITH_API_ENDPOINT|${{ secrets.API_URL }}|g" ./job-application-frontend/index.html

      # Sync frontend folder to S3
      - name: Deploy to S3
        run: |
          aws s3 sync ./job-application-frontend s3://application-ui-app-afa --delete \
            --cache-control "max-age=0, no-cache, no-store, must-revalidate"

      # Invalidate CloudFront cache
      - name: Invalidate CloudFront cache
        run: |
          aws cloudfront create-invalidation \
            --distribution-id E36KAGJ6TDMRGW \
            --paths "/*"
